---
# tasks file for open-peripheral
#
# https://input.club/configurator/
# https://github.com/kiibohd/controller
- name: install kiibo dependancies
  apt:
    pkg:
      - dfu-util
    state: present
  tags: ['kiibohd']
- name: Install drivers for kiibo configurator
  get_url:
    url: https://raw.githubusercontent.com/kiibohd/controller/master/98-kiibohd.rules
    dest: /etc/udev/rules.d
  register: kiiboRules
  tags: ['kiibohd']

- name: Reload udevadm
  when: kiiboRules.changed
  command: "udevadm control --reload-rules"
  tags: ['packages', 'kiibohd']

- name: Trigger udevadm
  when: kiiboRules.changed
  command: "udevadm trigger"
  tags: ['packages', 'kiibohd']

- name: Check to see if IC configurator exists already
  stat: 
    path: /usr/local/bin/kiibohd-configurator
  register: kiibohd_bin_exists
  tags: ['packages', 'kiibohd']

- name: Download the IC Configurator
  get_url:
    url: https://github.com/kiibohd/configurator/releases/download/v1.0.2/kiibohd-configurator-1.0.2-linux-x86_64.AppImage
    dest: "/usr/local/bin/kiibohd-configurator"
    mode: "+x"
  register: kiiboConfigurator
  tags: ['packages', 'kiibohd']
  when: not kiibohd_bin_exists.stat.exists






