---
- remote_user: root 
  become: false
  gather_facts: true
  hosts: pve

  tasks:

    - name: "Load the pve vault"
      include_vars:
        file: vault/pve
        name: pve_vault

    # Note: kind of hacky, you shouldn't log secret values here
    - name: Check variables are defined
      fail:
        msg: "{{ item }} is not defined"
      when: item is not defined
      with_items:
        - "{{ pve_admin_group }}"
        - "{{ pve_node }}"

    - name: "Create the {{ pve_admin_group }} group"
      proxmox_group:
        name: "{{ pve_admin_group }}"
  
    - name: "Create the {{ username }} user"
      proxmox_user:
        name: "{{ username }}@{{ pve_node }}"
        password: "{{ pve_vault.vaulted_pve_user_password }}"
        groups:
          - "{{ pve_admin_group }}"

    - name : "Create the {{ admin_acl_name }} ACL"
      proxmox_acl:
        path: /
        roles: [ "PVETemplateUser", "PVEVMAdmin" ]
        users:
          - "{{ username }}@{{ pve_node }}"



