- become: yes
  hosts: devmachine
  become_user: root
  become_method: su
  gather_facts: true
  roles:

    - role: vim-user
      become: no
      tags: ['vim']

    - role: bash-user
      become: no

    - role: kiibohd
      when: ansible_facts['os_family'] == 'Debian'

    - role: debian-devmachine
      when: ansible_facts['os_family'] == 'Debian'

    - role: arch-devmachine
      when: ansible_facts['os_family'] == 'Archlinux'

    - role: i3
    
    - role: qmk
