---

- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ lookup('env', 'HOME') }}/yay"
    update: true

- name: Build and install yay
  command:
    chdir: "{{ lookup('env', 'HOME') }}/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
