---

- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ lookup('env', 'HOME') }}/yay"
    update: true

- name: Build and install yay
  command:
    chdir: "{{ lookup('env', 'HOME') }}/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay

- name: Install pacman packages
  community.general.pacman:
    name: 
      - xorg-xmodmap
    state: present

- name: Add xmodmap file to home
  ansible.builtin.copy:
    src: xmodmap
    dest: "{{ lookup('env', 'HOME') }}/.Xmodmap"

- name: Update xmodmap configuration
  shell: "xmodmap {{ lookup('env', 'HOME') }}/.Xmodmap"
  changed_when: false

