---
# tasks file for roles/js-dev
- name: nvm
  become: no
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
    creates={{ ansible_env.HOME }}/.nvm/nvm.sh


