---
# tasks file for devmachine
- import_tasks: arch.yml
  tags: ['arch']


- name: Load in custom  bash_aliases file
  ansible.builtin.copy:
    src: bash_aliases    
    dest: "{{ lookup('env', 'HOME')  }}/.bash_aliases"
    mode: 0644
  become: no
