---
# tasks file for devmachine
- import_tasks: arch.yml
  when:  ansible_distribution == 'Archlinux'

- import_tasks: ubuntu.yml
  when:  ansible_distribution == 'Ubuntu'

- import_tasks: js.yml
  become_user: tom

- name: Load in custom  bash_aliases file
  ansible.builtin.copy:
    src: bash_aliases    
    dest: "{{ lookup('env', 'HOME')  }}/.bash_aliases"
    mode: 0644
  become: no
