---
- apt:
    update_cache: yes
    cache_valid_time: 84400
  tags: ['packages']

- name: Remove apt packages
  apt:
    pkg:
      - nano
    state: absent
  tags: ['packages']

- name: Install apt packages
  apt:
    pkg:
      - snapd
      - firefox
      - chromium-browser
      - filezilla
      - nginx
      - vim
      - neofetch
      - virtualbox
      - net-tools
      - nmap
      - docker-compose
    state: present
  tags: ['packages']

- name: Install snaps
  community.general.snap:
    name:
      - spotify
    state: present
  tags: ['packages']


- name: Install snaps in classic mode
  community.general.snap:
    state: present
    name:
      - code
      - sublime-text
    classic: yes
  tags: ['packages']


